// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVJOs9yBm1mKI2iamzQWRKHrEPhPEn1Rc',
    appId: '1:175165312979:web:340bb426e73a9124c72926',
    messagingSenderId: '175165312979',
    projectId: 'chatapp-92263',
    authDomain: 'chatapp-92263.firebaseapp.com',
    storageBucket: 'chatapp-92263.appspot.com',
    measurementId: 'G-FB92XT8QEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJSQoJTjUl-_X_h-lX0M5T8S9i20hQ82Q',
    appId: '1:175165312979:android:0766e61a57b88018c72926',
    messagingSenderId: '175165312979',
    projectId: 'chatapp-92263',
    storageBucket: 'chatapp-92263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7f0w640B4zCpy1T8H9XEBE4tAdLpQTO0',
    appId: '1:175165312979:ios:0ebb88edde3cd0bac72926',
    messagingSenderId: '175165312979',
    projectId: 'chatapp-92263',
    storageBucket: 'chatapp-92263.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
